# Generated by Django 5.1.2 on 2024-11-07 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsor', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sponsor',
            field=models.ManyToManyField(related_name='spons', through='Sponsor.User_Sponsor', to=settings.AUTH_USER_MODEL),
        ),
    ]
