# Generated by Django 5.1.2 on 2024-11-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='admin',
        ),
    ]
