# Generated by Django 5.1.2 on 2024-11-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_remove_feedback_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='url_images_feedback',
        ),
    ]
