# Generated by Django 5.1.2 on 2024-11-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auteur',
        ),
    ]
