# Generated by Django 5.1.2 on 2024-11-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_event_u_event_alter_user_event_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='u_event',
        ),
    ]
