# Generated by Django 4.2.16 on 2024-11-15 06:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categ', models.CharField(max_length=100)),
                ('desc_categ', models.TextField()),
                ('is_specifique', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_activite', models.CharField(max_length=100)),
                ('description_activite', models.TextField()),
                ('prix_activite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('localisation', models.CharField(max_length=255)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='Activity.category')),
            ],
        ),
        migrations.CreateModel(
            name='User_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity.activity')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'activity')},
            },
        ),
    ]
