# Generated by Django 5.1.2 on 2024-11-07 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categ', models.CharField(max_length=100)),
                ('desc_categ', models.TextField()),
                ('is_specifique', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_img', models.URLField()),
                ('ordre_img', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_activite', models.CharField(max_length=100)),
                ('description_activite', models.TextField()),
                ('prix_activite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('localisation', models.CharField(max_length=255)),
                ('note_moyenne', models.FloatField()),
                ('icone_map', models.CharField(max_length=255)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='Activity.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comm', models.TextField()),
                ('is_ban', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity.activity')),
            ],
        ),
    ]
