# Generated by Django 5.1.2 on 2024-11-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_activity_reservation_alter_activity_note_moyenne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='reservation',
        ),
    ]
