# Generated by Django 5.1.3 on 2024-11-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_utilisateur_username_alter_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
