# Generated by Django 4.2.16 on 2024-11-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='abonnement_user',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_premium_user',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='ticket_user',
        ),
    ]
